/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wellington.gerenciadorDeManobras.apresentacao;

import java.util.List;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import wellington.gerenciadorDeManobras.entidade.Categoria;
import wellington.gerenciadorDeManobras.entidade.Manobra;
import wellington.gerenciadorDeManobras.excecao.CampoObrigatorioException;
import wellington.gerenciadorDeManobras.negocio.CategoriaBO;
import wellington.gerenciadorDeManobras.negocio.ManobraBO;

/**
 *
 * @author were
 */
public class FormCadastroManobra extends javax.swing.JFrame {

    private Manobra manobraEmEdicao;
    private List<Categoria> categorias;
    private InfoManobras infoManobra;
   // public int verificaEditar;
    
    /**
     * Creates new form FormCadastroManobra
     */
    public FormCadastroManobra() throws SQLException {
      this.initComponents();
        this.carregarComboCategorias();
    }

   

//    FormCadastroManobra(InfoManobras aThis, Manobra manobraSelecionado) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

//    public int getVerificaEditar() {
//        return verificaEditar;
//    }
//
//    void setVerificaEditar(int verificaEditar) {
//        this.verificaEditar = verificaEditar;
//    }
//    
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeManobra = new javax.swing.JTextField();
        lblNomeManobra = new javax.swing.JLabel();
        lblDificuldade = new javax.swing.JLabel();
        cbxGrauDificuldade = new javax.swing.JComboBox();
        lblDificuldade1 = new javax.swing.JLabel();
        cbxStatusManobra = new javax.swing.JComboBox();
        lblDificuldade2 = new javax.swing.JLabel();
        lblDificuldade3 = new javax.swing.JLabel();
        cbxCategoriaManobras = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Manobra");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Manobra"));

        txtNomeManobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeManobraActionPerformed(evt);
            }
        });

        lblNomeManobra.setText("Nome");

        lblDificuldade.setText("Grau Dificulade");

        cbxGrauDificuldade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        cbxGrauDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGrauDificuldadeActionPerformed(evt);
            }
        });

        lblDificuldade1.setText("Status ");

        cbxStatusManobra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));
        cbxStatusManobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStatusManobraActionPerformed(evt);
            }
        });

        lblDificuldade2.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        lblDificuldade2.setText("(1: já sabe fazer, 2: não sabe fazer)");

        lblDificuldade3.setText("Categoria");

        cbxCategoriaManobras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "" }));
        cbxCategoriaManobras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaManobrasActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeManobra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeManobra, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDificuldade3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxCategoriaManobras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDificuldade1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxStatusManobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDificuldade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxGrauDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDificuldade2)))
                .addGap(0, 310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeManobra)
                    .addComponent(txtNomeManobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDificuldade)
                    .addComponent(cbxGrauDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDificuldade1)
                    .addComponent(cbxStatusManobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDificuldade2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoriaManobras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDificuldade3))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeManobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeManobraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeManobraActionPerformed

    private void cbxStatusManobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatusManobraActionPerformed


    }//GEN-LAST:event_cbxStatusManobraActionPerformed

    private void cbxGrauDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGrauDificuldadeActionPerformed

    }//GEN-LAST:event_cbxGrauDificuldadeActionPerformed

    private void cbxCategoriaManobrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaManobrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaManobrasActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        this.salvarManobra();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void salvarManobra() {
        try {

            this.validarCamposObrigatorios();
            this.recuperarCamposTela();
            ManobraBO manobraBO = new ManobraBO();
            manobraBO.inserir(manobraEmEdicao);

            JOptionPane.showMessageDialog(this, "Manobra cadastrada com sucesso!", "Cadastro de aluno", JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposTela();
            this.infoManobra.carregarTabelaDeManobras();

        } catch (ParseException e) {
            String mensagem = "Erro ao realizar operação:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de manobra", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            String mensagem = "Erro ao realizar operação:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de manobra", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void validarCamposObrigatorios() throws CampoObrigatorioException {
        if (txtNomeManobra.getText().trim().isEmpty()) {
            throw new CampoObrigatorioException();

        }
    }

    private void recuperarCamposTela() throws ParseException {
        manobraEmEdicao = new Manobra();
        manobraEmEdicao.setNome(txtNomeManobra.getText());
        
        int posicaoSelecionada1 = cbxGrauDificuldade.getSelectedIndex();
        manobraEmEdicao.setDificuldade(posicaoSelecionada1);

        int posicaoSelecionada2 = cbxStatusManobra.getSelectedIndex();
        manobraEmEdicao.setStatus(posicaoSelecionada2);

        int posicaoSelecionada3 = cbxCategoriaManobras.getSelectedIndex();
        manobraEmEdicao.setCategoria(posicaoSelecionada3);
    }

    private void limparCamposTela() {
        this.txtNomeManobra.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxCategoriaManobras;
    private javax.swing.JComboBox cbxGrauDificuldade;
    private javax.swing.JComboBox cbxStatusManobra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblDificuldade1;
    private javax.swing.JLabel lblDificuldade2;
    private javax.swing.JLabel lblDificuldade3;
    private javax.swing.JLabel lblNomeManobra;
    private javax.swing.JTextField txtNomeManobra;
    // End of variables declaration//GEN-END:variables

    private void carregarComboCategorias() throws SQLException {
     
        CategoriaBO categoriaBO = new CategoriaBO();
        categorias = categoriaBO.buscarTodasCategorias();
        cbxCategoriaManobras.removeAllItems();
        for (Categoria categoria : categorias) {
            cbxCategoriaManobras.addItem(categoria.getId());
        }
     }
}
