/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wellington.gerenciadorDeManobras.apresentacao;

import java.util.List;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import wellington.gerenciadorDeManobras.entidade.Categoria;
import wellington.gerenciadorDeManobras.entidade.Manobra;
import wellington.gerenciadorDeManobras.excecao.CampoObrigatorioException;
import wellington.gerenciadorDeManobras.negocio.CategoriaBO;
import wellington.gerenciadorDeManobras.negocio.ManobraBO;

/**
 *
 * @author were
 */
public class FormCadastroManobra extends javax.swing.JFrame {

    private Manobra manobraEmEdicao;
    private List<Categoria> categorias;
    private List<Manobra> manobras;
    private InfoManobras infoManobra;
    private InfoManobras editarManobrasFor;
    public int verificaEditarOuSalvar;

    /**
     * Creates metodos construtuores FormCadastroManobra
     */
    public FormCadastroManobra(InfoManobras infoManobras, Manobra manobraSelecionada) throws ParseException, SQLException {
        this(infoManobras);
        this.manobraEmEdicao = manobraSelecionada;
        this.inicializaCampoNomeManobra();
    }

    public FormCadastroManobra(InfoManobras infoManobras) throws ParseException, SQLException {
        this.infoManobra = infoManobras;
        this.manobraEmEdicao = new Manobra();
        this.initComponents();
      
        this.recuperarCamposTela();
        this.carregarComboCategorias();

    }

    // sobreescrita do set visible para toda vz que a tela de cadastro de manobras estiver 'VISIBLE'
    // o combobox das categorias atualizar
    @Override
    public void setVisible(boolean exibir) {
        super.setVisible(exibir);
        if (exibir == true) {
            try {
                this.carregarComboCategorias();
            } catch (SQLException ex) {
                Logger.getLogger(FormCadastroManobra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

//     private void carregarComboGrauDificuldade() throws SQLException {
//        ManobraBO manobraBO = new ManobraBO();
//        manobras = manobraBO.buscarTodasManobras();
//        cbxGrauDificuldade.removeAllItems();
//        cbxGrauDificuldade.addItem("selecione");
//        for (Manobra m : manobras) {
//            cbxGrauDificuldade.addItem(m.getDificuldade());
//        }
//    }
    private void carregarComboCategorias() throws SQLException {

        CategoriaBO categoriaBO = new CategoriaBO();
        categorias = categoriaBO.buscarTodasCategorias();
        cbxCategoriaManobras.removeAllItems();
        for (Categoria categoria : categorias) {
            cbxCategoriaManobras.addItem(categoria.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeManobra = new javax.swing.JTextField();
        lblNomeManobra = new javax.swing.JLabel();
        lblDificuldade = new javax.swing.JLabel();
        cbxGrauDificuldade = new javax.swing.JComboBox();
        lblDificuldade1 = new javax.swing.JLabel();
        cbxStatusManobra = new javax.swing.JComboBox();
        lblDificuldade2 = new javax.swing.JLabel();
        lblDificuldade3 = new javax.swing.JLabel();
        cbxCategoriaManobras = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Manobra");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Manobra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        txtNomeManobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeManobraActionPerformed(evt);
            }
        });

        lblNomeManobra.setText("Nome");

        lblDificuldade.setText("Grau Dificulade");

        cbxGrauDificuldade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        cbxGrauDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGrauDificuldadeActionPerformed(evt);
            }
        });

        lblDificuldade1.setText("Status ");

        cbxStatusManobra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "1" }));
        cbxStatusManobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStatusManobraActionPerformed(evt);
            }
        });

        lblDificuldade2.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        lblDificuldade2.setText("(1: já sabe fazer, 2: não sabe fazer)");

        lblDificuldade3.setText("Categoria");

        cbxCategoriaManobras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaManobrasActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeManobra)
                            .addComponent(txtNomeManobra, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDificuldade)
                            .addComponent(cbxGrauDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDificuldade3)
                                    .addComponent(cbxCategoriaManobras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxStatusManobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblDificuldade1)
                                .addGap(18, 18, 18)
                                .addComponent(lblDificuldade2)))
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeManobra)
                    .addComponent(lblDificuldade3))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeManobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCategoriaManobras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDificuldade2)
                    .addComponent(lblDificuldade1)
                    .addComponent(lblDificuldade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxStatusManobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGrauDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeManobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeManobraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeManobraActionPerformed

    private void cbxStatusManobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatusManobraActionPerformed


    }//GEN-LAST:event_cbxStatusManobraActionPerformed

    private void cbxGrauDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGrauDificuldadeActionPerformed

    }//GEN-LAST:event_cbxGrauDificuldadeActionPerformed

    private void cbxCategoriaManobrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaManobrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaManobrasActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (verificaEditarOuSalvar == 1) {
            try {
                this.atualizar();
            } catch (CampoObrigatorioException ex) {
                Logger.getLogger(FormCadastroManobra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(FormCadastroManobra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FormCadastroManobra.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.incluirManobra();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void incluirManobra() {
        try {

            this.validarCamposObrigatorios();
            this.recuperarCamposTela();
            ManobraBO manobraBO = new ManobraBO();
            manobraBO.inserir(manobraEmEdicao);

            JOptionPane.showMessageDialog(this, "Manobra cadastrada com sucesso!", "Nova manobra", JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposTela();
            this.infoManobra.carregarTabelaDeManobras();

        } catch (ParseException e) {
            String mensagem = "Erro ao realizar operação:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Nova manobra", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            String mensagem = "Erro ao realizar operação:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Nova manobra", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void atualizar() throws CampoObrigatorioException, ParseException, SQLException {
        this.validarCamposObrigatorios();
        this.recuperarCamposTela();
        ManobraBO manobraBO = new ManobraBO();
        manobraBO.atualizar(manobraEmEdicao);
        JOptionPane.showMessageDialog(this, "Dados da manobra alterado com sucesso", "Ediçao de manobra", JOptionPane.INFORMATION_MESSAGE);
        this.limparCamposTela();
        this.infoManobra.carregarTabelaDeManobras();
    }

    private void validarCamposObrigatorios() throws CampoObrigatorioException {
        if (txtNomeManobra.getText().trim().isEmpty()) {
            throw new CampoObrigatorioException();

        }
    }

    public void inicializaCampoNomeManobra() {
        txtNomeManobra.setText(manobraEmEdicao.getNome());
    }

    private void recuperarCamposTela() throws ParseException {
       
        manobraEmEdicao.setNome(txtNomeManobra.getText());

        int posicaoSelecionada1 = cbxGrauDificuldade.getSelectedIndex();
        manobraEmEdicao.setDificuldade(posicaoSelecionada1);

        int posicaoSelecionada2 = cbxStatusManobra.getSelectedIndex();
        manobraEmEdicao.setStatus(posicaoSelecionada2);

        int posicaoSelecionada3 = cbxCategoriaManobras.getSelectedIndex();
        manobraEmEdicao.setCategoria(posicaoSelecionada3);
    }

    private void limparCamposTela() {
        this.txtNomeManobra.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxCategoriaManobras;
    private javax.swing.JComboBox cbxGrauDificuldade;
    private javax.swing.JComboBox cbxStatusManobra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblDificuldade1;
    private javax.swing.JLabel lblDificuldade2;
    private javax.swing.JLabel lblDificuldade3;
    private javax.swing.JLabel lblNomeManobra;
    private javax.swing.JTextField txtNomeManobra;
    // End of variables declaration//GEN-END:variables

    // setando variavel para poder diferenciar quando o usuario quer editar ou atualizar uma manobra ou se está 
    // querendo salvar uma nova manobra
    public int getVerificaEditarOuSalvar() {
        return verificaEditarOuSalvar;
    }

    public void setVerificaEditarOuSalvar(int editarManobrasFor) {
        this.verificaEditarOuSalvar = editarManobrasFor;

    }
}
