/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wellington.gerenciadorDeManobras.apresentacao;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import wellington.gerenciadorDeManobras.entidade.Categoria;
import wellington.gerenciadorDeManobras.entidade.Manobra;
import wellington.gerenciadorDeManobras.excecao.NoSelectionException;

import wellington.gerenciadorDeManobras.negocio.CategoriaBO;
import wellington.gerenciadorDeManobras.negocio.ManobraBO;

/**
 *
 * @author were
 */
public class GerenciarManobrasTelaInicial extends javax.swing.JFrame {

    private FormCadastroManobra formCadastroManobra;
    private FormCadastroManobra editarManobraForm;
    private GerenciarCategorias adicionarCategoriaForm;
    private GerenciarTreinos telaGerenciarTreinos;
    private GerenciarManobrasTelaInicial infoManobras;
    private GerenciarRequisitos gerenciarRequisitos;
    private List<Manobra> manobras;
    private List<Categoria> categorias;

    /**
     * Creates new form InfoManobras
     */
    public GerenciarManobrasTelaInicial() throws SQLException {
        prepararTela();
    }

    public void prepararTela() throws SQLException {
        try {
            this.initComponents();
            this.carregarTabelaDeManobras();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Manobras cadastrados", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaManobras = new javax.swing.JTable();
        btnNovaManobra1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnExcluirManobra = new javax.swing.JButton();
        btnEditarManobra = new javax.swing.JButton();
        btnVerRequisitos = new javax.swing.JButton();
        lblDica = new javax.swing.JLabel();
        barraDeMenuPrincipal = new javax.swing.JMenuBar();
        menuOpçoes = new javax.swing.JMenu();
        mnuItemNovoTreino = new javax.swing.JMenuItem();
        mnuItemNovaCategoria = new javax.swing.JMenuItem();
        mnuItemRelatorio = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manobras");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manobras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        tabelaManobras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaManobras);

        btnNovaManobra1.setText("Nova Manobra");
        btnNovaManobra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaManobra1ActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluirManobra.setText("Excluir");
        btnExcluirManobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirManobraActionPerformed(evt);
            }
        });

        btnEditarManobra.setText("Editar");
        btnEditarManobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarManobraActionPerformed(evt);
            }
        });

        btnVerRequisitos.setText("Ver Requisitos");
        btnVerRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRequisitosActionPerformed(evt);
            }
        });

        lblDica.setText("Ao usar o sistema pela 1ª vez, antes de adicionar uma manobra  insira as categorias as quais elas vão pertencer!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNovaManobra1)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarManobra)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerRequisitos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluirManobra)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair))
                            .addComponent(lblDica, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaManobra1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarManobra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirManobra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menuOpçoes.setText("Opções");

        mnuItemNovoTreino.setText("Treino");
        mnuItemNovoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNovoTreinoActionPerformed(evt);
            }
        });
        menuOpçoes.add(mnuItemNovoTreino);

        mnuItemNovaCategoria.setText("Categoria");
        mnuItemNovaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNovaCategoriaActionPerformed(evt);
            }
        });
        menuOpçoes.add(mnuItemNovaCategoria);

        mnuItemRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemRelatorio.setText("Relatórios");
        menuOpçoes.add(mnuItemRelatorio);

        itemMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuOpçoes.add(itemMenuSair);

        barraDeMenuPrincipal.add(menuOpçoes);

        setJMenuBar(barraDeMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void mnuItemNovaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNovaCategoriaActionPerformed
        try {
            // TODO add your handling code here:
            this.carregarFormCadastroCategoria();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnuItemNovaCategoriaActionPerformed

    private void btnEditarManobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarManobraActionPerformed
        try {
            this.editarManobra();
            this.editarManobraForm.setVerificaEditarOuSalvar(1);
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEditarManobraActionPerformed

    private void btnExcluirManobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirManobraActionPerformed
        try {
            this.excluirManobra();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirManobraActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovaManobra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaManobra1ActionPerformed
        try {
            // TODO add your handling code here:
            this.carregarFormCadastroManobra();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNovaManobra1ActionPerformed

    private void mnuItemNovoTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNovoTreinoActionPerformed
        try {
            this.carregarFomrNovoTreino();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuItemNovoTreinoActionPerformed

    private void btnVerRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRequisitosActionPerformed
        try {
            this.carregarTelaGerenciarRequisitos();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerRequisitosActionPerformed

    private void carregarFormCadastroCategoria() throws SQLException {
        if (adicionarCategoriaForm == null) {
            adicionarCategoriaForm = new GerenciarCategorias();
        }
        adicionarCategoriaForm.setVisible(true);
        adicionarCategoriaForm.toFront();
    }

    private void carregarFomrNovoTreino() throws SQLException {
        if (telaGerenciarTreinos == null) {
            this.telaGerenciarTreinos = new GerenciarTreinos();
        }
        telaGerenciarTreinos.setVisible(true);
        telaGerenciarTreinos.toFront();
    }

    private void carregarFormCadastroManobra() throws SQLException, ParseException {
        if (formCadastroManobra == null) {
            formCadastroManobra = new FormCadastroManobra(this);
        }
        formCadastroManobra.setVisible(true);
        formCadastroManobra.toFront();

    }

    @Override
    public void setVisible(boolean exibir) {
        super.setVisible(exibir);
        if (exibir == true) {
            try {
                this.carregarTabelaDeManobras();
            } catch (SQLException ex) {
                Logger.getLogger(FormCadastroManobra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void carregarTabelaDeManobras() throws SQLException {
        ManobraBO manobrasBO = new ManobraBO();
        this.manobras = manobrasBO.buscarTodasManobras();
        ModeloTabelaManobras modelo = new ModeloTabelaManobras();
        tabelaManobras.setModel(modelo);
    }

    public void carregarTelaGerenciarRequisitos() throws SQLException {
        if (gerenciarRequisitos == null) {
            gerenciarRequisitos = new GerenciarRequisitos();
        }
        gerenciarRequisitos.setVisible(true);
        gerenciarRequisitos.toFront();

    }

    public void excluirManobra() throws SQLException {
        try {
            int linhaSelecionada = tabelaManobras.getSelectedRow();
            if (linhaSelecionada != -1) {
                Manobra manobraSelecionado = manobras.get(linhaSelecionada);

                int resposta;
                String mensagem = "Desseja excluir manobra? " + manobraSelecionado.getNome();
                String titulo = "Exclusão de manobra";
                resposta = JOptionPane.showConfirmDialog(this, mensagem, titulo, JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_NO_OPTION) {
                    ManobraBO manobraBO = new ManobraBO();
                    manobraBO.removerManobra(manobraSelecionado.getId());
                    mensagem = "Manobra " + manobraSelecionado.getNome() + " Id: " + manobraSelecionado.getId() + " excluída com sucesso!";
                    JOptionPane.showMessageDialog(this, mensagem, "Exclusão de Manobra", JOptionPane.INFORMATION_MESSAGE);
                    this.carregarTabelaDeManobras();
                }

            } else {
                String mensagem = "Nenhum manobra selecionada.";
                JOptionPane.showMessageDialog(this, mensagem, "Exclusão de manobra", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Não possivel excluir uma manora q é requisito de outras.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Exclusão de manobra ", JOptionPane.ERROR_MESSAGE);
            //this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GerenciarManobrasTelaInicial().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenuPrincipal;
    private javax.swing.JButton btnEditarManobra;
    private javax.swing.JButton btnExcluirManobra;
    private javax.swing.JButton btnNovaManobra1;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVerRequisitos;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDica;
    private javax.swing.JMenu menuOpçoes;
    private javax.swing.JMenuItem mnuItemNovaCategoria;
    private javax.swing.JMenuItem mnuItemNovoTreino;
    private javax.swing.JMenuItem mnuItemRelatorio;
    private javax.swing.JTable tabelaManobras;
    // End of variables declaration//GEN-END:variables

    private void editarManobra() throws SQLException, ParseException {
        int linhaSelecionada = tabelaManobras.getSelectedRow();
        if (linhaSelecionada != -1) {
            Manobra manobraSelecionado = manobras.get(linhaSelecionada);
            if (editarManobraForm != null) {
                editarManobraForm.dispose();
            }
            editarManobraForm = new FormCadastroManobra(this, manobraSelecionado);
            editarManobraForm.setVisible(true);
        } else {
            throw new NoSelectionException();
        }
    }

    //classe interna
    private class ModeloTabelaManobras extends AbstractTableModel {

        @Override
        public String getColumnName(int coluna) {
            if (coluna == 0) {
                return "Nome";
            } else if (coluna == 1) {
                return "Dificuldade";
            } else if (coluna == 2) {
                return "Status";
            } else {
                return "Categoria";
            }
        }

        @Override
        public int getRowCount() {
            return manobras.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Manobra m = manobras.get(rowIndex);
            if (columnIndex == 0) {
                return m.getNome();
            } else if (columnIndex == 1) {

                if (m.getDificuldade() == 0) {
                    return "simples";
                } else if (m.getDificuldade() == 1) {
                    return "facil";
                } else if (m.getDificuldade() == 2) {
                    return "mediana";
                } else if (m.getDificuldade() == 3) {
                    return "difícil";
                } else if (m.getDificuldade() == 4) {
                    return "muito dificíl";
                }
                return null;

            } else if (columnIndex == 2) {
                if (m.getStatus() < 100) {
                    return "Não sabe fazer ainda";
                } else {
                    return "100%";
                }

            } else {
                if (columnIndex == 3) {
                    try {
                        CategoriaBO categoriaBO = new CategoriaBO();
                        categorias = categoriaBO.buscarTodasCategorias();
                        for (Categoria c : categorias) {
                            if (c.getId() == m.getCategoria()) {
                                return c.getNome();
                            }
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(GerenciarManobrasTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                return null;
            }

        }

    }
}
