/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wellington.gerenciadorDeManobras.apresentacao;

import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import wellington.gerenciadorDeManobras.entidade.Usuario;
import wellington.gerenciadorDeManobras.negocio.UsuarioBO;

/**
 *
 * @author Wellington
 */
public class Login extends javax.swing.JFrame {

    private Inicio telaInicio;
    private Usuario usuarioEmEdicao;
  
    private UsuarioBO usuarioBO;

    /**
     * Creates new form Login
     */
    public Login() {
         this.usuarioEmEdicao = new Usuario();
        initComponents();
    }

    public Login(Inicio telaInicio) {
        this.usuarioEmEdicao = new Usuario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionarNovoUser = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        txtSenhaNovo = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin1 = new javax.swing.JTextField();
        txtLoginNovo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar - Gerenciador De Manobras");
        getContentPane().setLayout(null);

        btnAdicionarNovoUser.setText("Criar Login");
        btnAdicionarNovoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarNovoUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarNovoUser);
        btnAdicionarNovoUser.setBounds(490, 200, 210, 40);

        btnEntrar.setText("Entrar");
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(10, 200, 210, 40);
        getContentPane().add(txtSenhaNovo);
        txtSenhaNovo.setBounds(490, 150, 210, 20);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(10, 150, 210, 20);

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bmx.jpg"))); // NOI18N
        getContentPane().add(lblLogin);
        lblLogin.setBounds(240, 60, 230, 220);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 80, 190, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Novo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 50, 190, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Login:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 190, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 190, 14);
        getContentPane().add(txtLogin1);
        txtLogin1.setBounds(10, 100, 210, 20);
        getContentPane().add(txtLoginNovo);
        txtLoginNovo.setBounds(490, 100, 210, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 130, 190, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Entrar!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 40, 190, 14);

        setSize(new java.awt.Dimension(745, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarNovoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarNovoUserActionPerformed
        try {
            this.usuarioBO.verificauUsuarioDuplicado(usuarioEmEdicao);
            this.incluiUsuario();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarNovoUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarNovoUser;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtLogin1;
    private javax.swing.JTextField txtLoginNovo;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSenhaNovo;
    // End of variables declaration//GEN-END:variables

    private void incluiUsuario() throws NoSuchAlgorithmException, UnsupportedEncodingException, SQLException {
        this.usuarioEmEdicao = new Usuario();
        this.recuperarCamposTela();

        this.usuarioBO = new UsuarioBO();
        this.usuarioBO.incluirUsuario(usuarioEmEdicao);
        JOptionPane.showMessageDialog(this, "Novo usuário cadastrado com sucesso! Agora Tente Efetuar seu Login!", "Nova Usuário", JOptionPane.INFORMATION_MESSAGE);

    }

    private void recuperarCamposTela() throws SQLException {
        usuarioEmEdicao.setLogin(txtLoginNovo.getText());
        usuarioEmEdicao.setSenha(txtSenhaNovo.getText());
    }

   
}
