/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wellington.gerenciadorDeManobras.apresentacao;

/**
 *
 * @author Wellington
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionarNovoUser = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        txtSenhaNovo = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin1 = new javax.swing.JTextField();
        txtLoginNovo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar - Gerenciador De Manobras");
        getContentPane().setLayout(null);

        btnAdicionarNovoUser.setText("Criar Login");
        getContentPane().add(btnAdicionarNovoUser);
        btnAdicionarNovoUser.setBounds(490, 200, 210, 40);

        btnEntrar.setText("Entrar");
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(10, 200, 210, 40);
        getContentPane().add(txtSenhaNovo);
        txtSenhaNovo.setBounds(490, 150, 210, 20);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(10, 150, 210, 20);

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bmx.jpg"))); // NOI18N
        getContentPane().add(lblLogin);
        lblLogin.setBounds(240, 60, 230, 220);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 80, 190, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Novo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 50, 190, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Login:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 190, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 190, 14);
        getContentPane().add(txtLogin1);
        txtLogin1.setBounds(10, 100, 210, 20);
        getContentPane().add(txtLoginNovo);
        txtLoginNovo.setBounds(490, 100, 210, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 130, 190, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Entrar!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 40, 190, 14);

        setSize(new java.awt.Dimension(745, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarNovoUser;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtLogin1;
    private javax.swing.JTextField txtLoginNovo;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSenhaNovo;
    // End of variables declaration//GEN-END:variables
}
